In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/day.csv")

In [3]:
df.head()

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,6,0,2,0.344167,0.363625,0.805833,0.160446,331,654,985
1,2,2011-01-02,1,0,1,0,0,0,2,0.363478,0.353739,0.696087,0.248539,131,670,801
2,3,2011-01-03,1,0,1,0,1,1,1,0.196364,0.189405,0.437273,0.248309,120,1229,1349
3,4,2011-01-04,1,0,1,0,2,1,1,0.200000,0.212122,0.590435,0.160296,108,1454,1562
4,5,2011-01-05,1,0,1,0,3,1,1,0.226957,0.229270,0.436957,0.186900,82,1518,1600

In [4]:
total_data = len(df)

In [6]:
train_size = int(0.8 * total_data) #80% data training
test_size = total_data - train_size #20% data testing
val_size = int(0.1 * train_size) #10% dari training untuk validasi

In [7]:
train_full = df[:train_size]         # 80% pertama untuk training
test_df = df[train_size:]            # 20% terakhir untuk testing
val_df = train_full[:val_size]       # 10% awal dari training jadi validation
train_df = train_full[val_size:]     # sisa training

In [8]:
# menampilkan jumlah data
print("Jumlah total data:", total_data)
print("Jumlah data Training:", len(train_df))
print("Jumlah data Validation:", len(val_df))
print("Jumlah data Testing:", len(test_df))

print("\n--- Data Training (5 teratas) ---")
print(train_df.head())

print("\n--- Data Validation (5 teratas) ---")
print(val_df.head())

print("\n--- Data Testing (5 teratas) ---")
print(test_df.head())

Jumlah total data: 731
Jumlah data Training: 526
Jumlah data Validation: 58
Jumlah data Testing: 147

--- Data Training (5 teratas) ---
    instant      dteday  season  yr  mnth  holiday  weekday  workingday  \
58       59  2011-02-28       1   0     2        0        1           1
59       60  2011-03-01       1   0     3        0        2           1
60       61  2011-03-02       1   0     3        0        3           1
61       62  2011-03-03       1   0     3        0        4           1
62       63  2011-03-04       1   0     3        0        5           1

    weathersit      temp     atemp       hum  windspeed  casual  registered  \
58           2  0.407273  0.400118  0.876364   0.289686      81        1365
59           1  0.266667  0.263879  0.535000   0.216425     137        1714
60           1  0.335000  0.320071  0.449583   0.307833     231        1903
61           1  0.198333  0.200133  0.318333   0.225754     123        1562
62           2  0.261667  0.255679  0.610417   0.203346     214        1730

     cnt
58  1446
59  1851
60  2134
61  1685
62  1944

--- Data Validation (5 teratas) ---
   instant      dteday  season  yr  mnth  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1        0        6           0
1        2  2011-01-02       1   0     1        0        0           0
2        3  2011-01-03       1   0     1        0        1           1
3        4  2011-01-04       1   0     1        0        2           1
4        5  2011-01-05       1   0     1        0        3           1

   weathersit      temp     atemp       hum  windspeed  casual  registered  \
0           2  0.344167  0.363625  0.805833   0.160446     331         654
1           2  0.363478  0.353739  0.696087   0.248539     131         670
2           1  0.196364  0.189405  0.437273   0.248309     120        1229
3           1  0.200000  0.212122  0.590435   0.160296     108        1454
4           1  0.226957  0.229270  0.436957   0.186900      82        1518

    cnt
0   985
1   801
2  1349
3  1562
4  1600

--- Data Testing (5 teratas) ---
     instant      dteday  season  yr  mnth  holiday  weekday  workingday  \
584      585  2012-08-07       3   1     8        0        2           1
585      586  2012-08-08       3   1     8        0        3           1
586      587  2012-08-09       3   1     8        0        4           1
587      588  2012-08-10       3   1     8        0        5           1
588      589  2012-08-11       3   1     8        0        6           0

     weathersit      temp     atemp       hum  windspeed  casual  registered  \
584           2  0.735833  0.697621  0.703750   0.116908    1278        5995
585           2  0.750000  0.707717  0.672917   0.110700    1263        6271
586           1  0.755833  0.699508  0.620417   0.156100    1196        6090
587           2  0.715833  0.667942  0.715833   0.238813    1065        4721
588           2  0.692500  0.638267  0.732917   0.206479    2247        4052

      cnt
584  7273
585  7534
586  7286
587  5786
588  6299